# Generated by Django 3.0.8 on 2020-08-03 22:17

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgeter', '0003_auto_20200803_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='budget',
            name='budget_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='budget',
            name='allowed_spending',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='budget_name',
            field=models.CharField(max_length=200, verbose_name='Nome do Orçamento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgeter.Budget', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Despesa'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='budget_start_day',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28')], default=1, verbose_name='Dia de inicio do orçamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Orçamento Total'),
        ),
    ]
